print("Zadej číslo")
cislo1 = int(input())
print("Teď zadej znaménko")
znamenko = input()
print("Dobře a ještě druhé číslo")
cislo2 = int(input())
soucet = (cislo1 + cislo2)
rozdil = (cislo1 - cislo2)
soucin = (cislo1 * cislo2)
podil = (cislo1 / cislo2)
vysledek = (soucet or rozdil or soucin or podil)
print("Dobře zde je výsledek")
print(vysledek)